### ISSUE TITLE
Async variation of fetching the current account crashes on force unwrap of previous account

### ISSUE THREAD

**Issue by brandonsmarthome** [AzureAD/microsoft-authentication-library-common-for-objc#1141]
I'm using version 1.2.3 of this library on Xcode 13.4.1.

MSAL has a function for fetching the current account on the application context:
```swift
applicationContext.getCurrentAccount(with: msalParameters) { currentAccount, previousAccount, error in
    ....
}
```
This is the callback variation of that function. Inside of the callback, are three **_optional_** values. This function works exactly as expected.

The library also provides an async / await variation:
```swift
let (currentAccount, previousAccount) = try await applicationContext.currentAccount(with: msalParameters)
```
However, this function has a force unwrap that is crashing my app. In the callback function, the return values are all optional but in this async / await function the return values are force unwrapped. If you attempt to get the current account on a fresh simulator with no previously signed in accounts, the app will crash.

**Proposed Solution**
Have the async / await function return optional values for the current account and previous account to match the functionality of the callback function.

**Comment by kaisong1990** [comment]
@brandonsmarthome  We are actively looking into the issue, and testing a potential fix.

**Comment by kaisong1990** [comment]
@brandonsmarthome You issue should be addressed in our release, can you give a try?

**Comment by kaisong1990** [comment]
No active conversations, closing
