### ISSUE TITLE
Veracode Flaw CWE ID 297 Improper Validation of Certificate with Host Mismatch

### ISSUE THREAD

**Issue by Joanatasfernandes-iteam** [AzureAD/microsoft-authentication-library-common-for-objc#1254]
Estou me deparando com o mesmo problema relatato a 3 anos atrás e ainda não consegui uma resposta com uma possivel solução para este problema, gostaria de apoio para entender melhor como funciona essa implementação e como poderia tratar essa falha de melhor maneira. 
![StackOverFlow](https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/assets/110417267/0f83bf73-f0fe-4a0f-8039-e6347043c87e)

**Comment by swasti29** [comment]
@Joanatasfernandes-iteam This seems wrong repository for this issue. Kindly reach out again with more information if that is not the case.
