### ISSUE TITLE
Adding Known Authorities

### ISSUE THREAD

**Issue by marksands** [AzureAD/microsoft-authentication-library-common-for-objc#454]
We are using MSAL and noticed the `validateAuthority` property is deprecated in favor of adding known authorities. We added our `MSALAuthority` B2C domains, but when the code gets to this line:

https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/blob/1304ddfce299784585de5c513deb09658bd7a440/IdentityCore/src/validation/MSIDAuthority.m#L160

It's not looking at *our* configuration, so the authority is not known. This seems like a bug or we are using the API incorrectly. Please advise.

**Comment by unpluggedk** [comment]
@marksands can you please share how you are using this? (i.e./ how are you adding it to known authorities?)

**Comment by marksands** [comment]
@unpluggedk 

roughly, this is what our (obfuscated) code looks like:

```
let url = URL(string: "https://example.b2clogin.com/tfp/example.onmicrosoft.com/B2C_dev_SignIn")!
let authority = try? MSALAuthority(url: url)
let app = try MSALPublicClientApplication(clientId: b2cClientId, authority: authority)
```

**Comment by oldalton** [comment]
Hi, sorry for our late reply. You should set known authorities in the MSALPublicClientApplicationConfig: https://github.com/AzureAD/microsoft-authentication-library-for-objc/blob/dev/MSAL/src/public/configuration/MSALPublicClientApplicationConfig.h#L54.

So, after creating your MSALAuthority, set knownAuthorities to an array containing your MSALAuthority objects.

**Comment by marksands** [comment]
```
let url = URL(string: "https://example.b2clogin.com/tfp/example.onmicrosoft.com/B2C_dev_SignIn")!
let authority = try? MSALAuthority(url: url)
let app = try MSALPublicClientApplication(clientId: b2cClientId, authority: authority)
app.configuration.knownAuthorities = [authority]
```

Ok we did the above, by setting the configuration's known authorities to the authority. However, when we run the application against that validation we are getting an error back from MSAL:

```
Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=Authority validation is not supported for this type of authority, MSALInternalErrorCodeKey=-50000, MSALCorrelationIDKey=708C5874-2C50-417D-A14D-5A14C1E5E5C6}
```

Diving into the code a little bit, it eventually gets to this statement https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/blob/master/IdentityCore/src/validation/MSIDAuthority.m#L160 which is only checking against these authorities:

```
    "login-us.microsoftonline.com",
    "login.chinacloudapi.cn",
    "login.windows.net",
    "login.partner.microsoftonline.cn",
    "login.microsoftonline.de",
    "login.microsoftonline.com",
    "login.usgovcloudapi.net",
    "login.microsoftonline.us"
```

So how can we add our custom authority to the list of trusted hosts? Or is this a bug/TODO in the framework? I did see a comment in the `isKnown` method that says `    // TODO: Can we move it out from here? What about ADFS & B2C?` 😉

**Comment by oldalton** [comment]
@marksands, configuration is readonly after its creation. You cannot update configuration after you create the app. 
You should create configuration first, set your known authorities, pass configuration in the initializer to the MSALPublicClientApplication. Let me know if it helps. Thanks!

**Comment by marksands** [comment]
@oldalton thank you! That worked!

One suggestion to prevent someone else from making this mistake would be to add `readonly` attributes for the properties on the client application config https://github.com/AzureAD/microsoft-authentication-library-for-objc/blob/dev/MSAL/src/public/configuration/MSALPublicClientApplicationConfig.h#L42-L72

**Comment by oldalton** [comment]
Thanks, @marksands. We tried to follow what Apple does with [WKWebViewConfiguration](https://developer.apple.com/documentation/webkit/wkwebviewconfiguration?language=objc) and [WKWebView initializer](https://developer.apple.com/documentation/webkit/wkwebview/1414998-initwithframe?language=objc).

When we worked on this API, it was a bit tricky to make those properties readonly as we didn't want to require developer to pass all optional properties in the initializer. We want the pattern to be the following:

1. Create config with mandatory attributes
2. Set any additional optional attributes through readwrite properties
3. Pass configuration to the MSALPublicClientApplication

Do you think it would be more intuitive to have all properties being passed to the initializer in configuration, and make all properties readonly? Or perhaps we can remove readonly configuration from MSALPublicClientApplication to avoid developers trying to set attributes after initialization? 

Would appreciate feedback/additional suggestions?

Thanks!

**Comment by marksands** [comment]
Thank you for your reasoning, I hadn't put much thought into it. 👍 

The configuration API works better for `WKWebView`'s initializer since `WKWebViewConfiguration` is always a required parameter for initialization. We were initially using the `MSALPublicClientApplication(clientId:authority:)` initializer which doesn't take a configuration therefore avoiding custom knownAuthorities. Allowing developers to set the configuration after initialization might be an easy solution, but I'm not sure if that would introduce unknown side effects to the existing library.

A good place to start would be better documentation. Since the default setting is to validate the authority, the existing error message without setting a custom configuration states `"Authority validation is not supported for this type of authority"`. Better phrasing might suggest opting out of the validation by specifying the knownAuthorities in the `MSALPublicClientApplicationConfig` when constructing your `MSALPublicClientApplication` instance.

Thank you for the assistance so far! 🙂

**Comment by marksands** [comment]
Looking through this further, it looks like there's already a deprecation warning on the validateAuthority property https://github.com/AzureAD/microsoft-authentication-library-for-objc/blob/dev/MSAL/src/public/MSALPublicClientApplication.h#L57, so that's great!

**Comment by ReactNativeRD2019** [comment]
I have Created MSPublicClientApplicationConfig object and passed it to MSPublicClientApplication. Still getting  this issue

Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=Authority validation is not supported for this type of authority, MSALInternalErrorCodeKey=-50000, MSALCorrelationIDKey=708C5874-2C50-417D-A14D-5A14C1E5E5C6}

**Comment by oldalton** [comment]
@ReactNativeRD2019, have you passed your authority into the "knownAuthorities" property?
