### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by mitchdenny** [AzureAD/microsoft-authentication-library-common-for-objc#684]
Are the maintainers of this repository considering adding support for the Swift Package Manager? This library is a dependency of MSAL for Objective-C where the exact same question has been asked:

https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/737

In order for that issue to get addressed this library would either need to be folded into it (not via a submodule) or as a Swift Package that could be imported as a dependency.

**Comment by rohitnarula7176** [comment]
Closing this as duplicate. It is being tracked here:
https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/737
