### ISSUE TITLE
ADCacheToken.h should be moved out of mac folder

### ISSUE THREAD

**Issue by ruixi1994** [AzureAD/microsoft-authentication-library-common-for-objc#689]
"src/deps/adalobjc/ADAL/src/public/Mac/ADTokenCache.h"
This file only has Mac version, but it will be included in ADAuthenticationContext which compiles for iOS.

**Comment by rohitnarula7176** [comment]
@ruixi1994 Thank you for reporting this.

**Comment by oldalton** [comment]
This should be fixed in latest ADAL lib.
