### ISSUE TITLE
Requesting SP800-108 implementation be moved from token broker to common core

### ISSUE THREAD

**Issue by kevindiclemente** [AzureAD/microsoft-authentication-library-common-for-objc#708]
MSAL needs to use SP800-108 HMAC on MacOS, and support for this exists today in token broker. I believe both MSAL and token broker have a dependency on common core, so this would be a great spot to refactor this code for shared usage

https://github.com/AzureAD/azure-activedirectory-tokenbroker-for-objc/blob/master/ADAuthenticationBroker/ADAuthenticationBroker/ADBrokerCryptoProvider.m#L77

**Comment by rohitnarula7176** [comment]
Discussed with @kevindiclemente and this issue has been addressed.
