### ISSUE TITLE
Remove UIWebView reference

### ISSUE THREAD

**Issue by Dimillian** [AzureAD/microsoft-authentication-library-common-for-objc#735]
You have one reference to UIWebView in a comment: 
https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/blob/28f1d88eac8c055a6eee8616414622173102679c/IdentityCore/src/webview/embeddedWebview/challangeHandlers/ios/MSIDCertAuthHandler.m#L165

This make App Store Connect to reject the binary on new application and trigger a warning on already shipped application.

> ITMS-90809: Deprecated API Usage - App updates that use UIWebView will no longer be accepted as of December 2020. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

Thanks!

**Comment by oldalton** [comment]
Good catch! Removed it from the comment here:https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/pull/729/commits/adc9f87aaf60b693f7d5bffb8a5bb8705d2a63c5. 

It will be included in the next MSAL release (1.1.3). Thanks.

**Comment by Dimillian** [comment]
Perfect thanks! 👍

**Comment by oldalton** [comment]
Fixed in MSAL 1.1.3. Closing the issue.
