### ISSUE TITLE
CustomWebViewHeaders shouldn't be mutable

### ISSUE THREAD

**Issue by oldalton** [AzureAD/microsoft-authentication-library-common-for-objc#753]
MSIDInteractiveRequestParameters.h file specifies customWebviewHeaders as a NSMutableDictionary. It should be NSDictionary instead. 

`@property (readwrite) NSMutableDictionary<NSString *, NSString *> *customWebviewHeaders;
`

in https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/blob/dev/IdentityCore/src/parameters/MSIDInteractiveRequestParameters.h#L37

**Comment by kaisong1990** [comment]
CustomWebViewHeaders was converted to immutable in this PR

https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/pull/857
