### ISSUE TITLE
Veracode - Improper Validation of Certificate with Host Mismatch 😱

### ISSUE THREAD

**Issue by bitops** [AzureAD/microsoft-authentication-library-common-for-objc#809]
Hello friends, a Veracode run against an app using MSAL produced this alert. Veracode considers it a "Medium."

Offending line of code on [line 44 of MSIDURLSessionDelegate.m](https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/blob/b4ca2ddc4507ad27576ad28540374c749685ed51/IdentityCore/src/network/session_delegate/MSIDURLSessionDelegate.m#L44)

## Veracode output

**Description:** In this call to MSIDURLSessionDelegate.completionHandler:(), host-specific certificate data is not validated or is incorrectly validated. Failing to validate the certificate makes the SSL session susceptible to a man-in-the-middle attack.

**Remediation:** Verify that the certificate is valid, matches the requested site, and is signed by a trusted root authority. Generate an error and destroy the connection if any of these conditions are not met.
##

Is this anything to worry about?

**Comment by oldalton** [comment]
Thanks for filing this issue. Wouldn't OS take care of certificate validation in case of default handling already?

**Comment by bitops** [comment]
That seems like a pretty reasonable assumption to me? But that said, I am not a security expert by any means. Possibly this is a false positive on Veracode's part.

**Comment by bitops** [comment]
@oldalton I did a little more research on this and it seems it's possible the default handler will not take care of certificate validation. I found a [CWE here](https://cwe.mitre.org/data/definitions/297.html) that seems to indicate it's possibly a common problem.

From what I turned up, it seems like [Certificate Pinning](https://www.netguru.com/codestories/certificate-pinning-in-ios) is the recommended solution.

With that said, this may still be a false positive.

**Comment by bitops** [comment]
It also seems I am not the first person to file tickets against teams at Microsoft based on Veracode runs. This [issue here](https://github.com/microsoft/appcenter-sdk-android/issues/1316) at least seems to suggest that. Possibly someone on a different team has dealt with this before.

**Comment by oldalton** [comment]
Thanks. We don't provide certificate pinning functionality at this point. 
Certificate pinning would harden security on top of OS security model, but MSAL's security is as good as OS security at this point.

**Comment by bitops** [comment]
@oldalton thank you - I suppose we can close the issue in that case. 👍🏻

Will certificate pinning be supported in the future?

**Comment by antrix1989** [comment]
We don't have any plans to support cert pinning at this moment.
