### ISSUE TITLE
Apply Xcode 12 recommended settings to stop it showing warnings in issue navigator

### ISSUE THREAD

**Issue by arangato** [AzureAD/microsoft-authentication-library-common-for-objc#826]
XCode 12 shows "Validate project settings" warning in issue navigator and suggests a number of updates.
In fact it's enough enabling only the whole module optimization (see below) to make it happy.

![image](https://user-images.githubusercontent.com/49146595/91685583-71196200-eb63-11ea-9191-80a6021bc6bb.png)

**Comment by arangato** [comment]
since I've already done it, here is a PR that does just that : https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/pull/827

**Comment by antrix1989** [comment]
@arangato, thank you for the contribution! We will review your pr.

**Comment by antrix1989** [comment]
The change is merged in dev.
