### ISSUE TITLE
Crash on handleMSALResponse from the broker application

### ISSUE THREAD

**Issue by aobolentsev** [AzureAD/microsoft-authentication-library-common-for-objc#912]
@implementation MSIDDeviceInfo

#pragma mark - MSIDJsonSerializable

- (instancetype)initWithJSONDictionary:(NSDictionary *)json error:(__unused NSError **)error
{
    self = [super init];
    
    if (self)
    {
        _deviceMode = [self deviceModeEnumFromString:[json msidStringObjectForKey:MSID_BROKER_DEVICE_MODE_KEY]];
        _ssoExtensionMode = [self ssoExtensionModeEnumFromString:[json msidStringObjectForKey:MSID_BROKER_SSO_EXTENSION_MODE_KEY]];
        _wpjStatus = [self wpjStatusEnumFromString:[json msidStringObjectForKey:MSID_BROKER_WPJ_STATUS_KEY]];
        _brokerVersion = [json msidStringObjectForKey:MSID_BROKER_BROKER_VERSION_KEY];
        
        NSData *jsonData = [json[MSID_ADDITIONAL_EXTENSION_DATA_KEY] dataUsingEncoding:NSUTF8StringEncoding];
///////// No data received and crash happens
        _additionalExtensionData = [NSJSONSerialization msidNormalizedDictionaryFromJsonData:jsonData error:nil];

**Comment by oldalton** [comment]
@aobolentsev, sorry for the late reply. I wasn't able to reproduce this issue on my end. Do you mind printing out the contents of json dictionary when a crash happens? Additionally, would be great if you could also provide an MSAL log and a crash stack. Thanks!
